// Axel Zuchovicki A01022875

#ifndef ERROR_CORRECTION_TOOLS_H
#define ERROR_CORRECTION_TOOLS_H

#define SEND_PARTS_STR "SEND ME YOUR PARTS"
#define DELETE_PART_STR "PERFORM CASTRATION"
#define RECEIVED_MESSAGE "RECEIVED MESSAGE"
#define NO_INFORMATION "NO INFORMATION TO SEND"
#define MAX_STR_LEN 1000000
#define MAX_PARITY_LEN 100000
#define MIN_PARALLEL_LEN 100

#endif //ERROR_CORRECTION_TOOLS_H
